# Generated by Django 2.1.15 on 2020-04-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_status_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='projet',
            new_name='project',
        ),
    ]
